Repository tablecheck/frontend, pull requests merged in 2021-09, with the labels that each got.

#25 deps: update typescript
  auditjs.json
  package-lock.json
  package.json
  packages/eslint-config/package.json
  packages/scripts/package.json
Labels: minor

#26 fix(scripts): add audit cli cache option
  packages/scripts/scripts/auditjs.js
Labels: bug, minor

#27 fix: add cypress types for odd edge cases
  packages/scripts/scripts/init.js
  packages/scripts/scripts/utils/configureTypescript.js
Labels: patch

#28 fix(scripts): turn off prop types rule
  packages/eslint-config/rules/react.js
Labels: bug, minor
